### ISSUE TITLE
Requires a reload to work

### ISSUE THREAD

**Issue by Jinnai** [doadin/PlexusAutoFrameSize#1]
Changes to the number of groups only causes the raid frames to grow/shrink without adjusting the position until the game is reloaded.

![image](https://user-images.githubusercontent.com/1058140/140727314-ea5d04dc-7c42-4e42-85d8-d80921003cc8.png)

![image](https://user-images.githubusercontent.com/1058140/140727325-64bf2624-476c-49d4-bdab-d6009035d686.png)

**Comment by doadin** [comment]
Sorry this has been so long, I hopefully have a fix just released, https://github.com/doadin/PlexusAutoFrameSize/commit/384dccf76ad2e47ea875ffda56114e84c93eeef7 .
